name: Publish preview update

on:
  push:
    branches: ['master']

    tags:
      - dev

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
